// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfDxOxZcieDs6-y45yjstI_C7ViJZPQFs',
    appId: '1:573761065588:web:9d8756b9193e66601ff721',
    messagingSenderId: '573761065588',
    projectId: 'siresep-project',
    authDomain: 'siresep-project.firebaseapp.com',
    storageBucket: 'siresep-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMlkxOwTp1EAue_qx-QjoN1SbgtkJNT8',
    appId: '1:573761065588:android:741a15fb7b2514391ff721',
    messagingSenderId: '573761065588',
    projectId: 'siresep-project',
    storageBucket: 'siresep-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmF030Y3gYDM3T_QHgBAfPzDt4Hm8oEA',
    appId: '1:573761065588:ios:eb5e3edb63cef0b01ff721',
    messagingSenderId: '573761065588',
    projectId: 'siresep-project',
    storageBucket: 'siresep-project.firebasestorage.app',
    iosBundleId: 'com.example.siresep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnmF030Y3gYDM3T_QHgBAfPzDt4Hm8oEA',
    appId: '1:573761065588:ios:eb5e3edb63cef0b01ff721',
    messagingSenderId: '573761065588',
    projectId: 'siresep-project',
    storageBucket: 'siresep-project.firebasestorage.app',
    iosBundleId: 'com.example.siresep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfDxOxZcieDs6-y45yjstI_C7ViJZPQFs',
    appId: '1:573761065588:web:fe94d4a46a05fb2b1ff721',
    messagingSenderId: '573761065588',
    projectId: 'siresep-project',
    authDomain: 'siresep-project.firebaseapp.com',
    storageBucket: 'siresep-project.firebasestorage.app',
  );
}
